### ISSUE TITLE
LC0 doesn't start when running infinite analysis. BUG

### ISSUE THREAD

**Issue by Chess321** [LeelaChessZero/lc0#1122] opened 2020-03-10 08:28 UTC
Fritz GUI
LC0 v0.24.0-rc2
2x RTX 2080 Ti
4 of 6 CPU cores
8 of 64 GB RAM
Tested with different nets and net size.

This happens sometimes from the beginning and sometimes after I clicked the first infinite analysis on and off and again on.
[logfile.txt](https://github.com/LeelaChessZero/lc0/files/4311106/logfile.txt)

**Comment by mooskagh** [comment] 2020-03-10 20:54
From the log file, it looks it's exactly the same issue as in #1120, but indeed it does look that something is wrong there.

I'm closing this issue as a duplicate of #1120, let's continue investigating there.

**Closed by mooskagh** 2020-03-10 20:54 UTC
