### ISSUE TITLE
LC0 doesn't start when running a test suite. BUG

### ISSUE THREAD

**Issue by Chess321** [LeelaChessZero/lc0#1120] opened 2020-03-10 07:53 UTC
Fritz GUI
LC0 v0.24.0-rc2 
2x RTX 2080 Ti
4 of 6 CPU cores
8 of 64 GB RAM
Tested with different nets and net size.

Testsuite is running but LC0 is doing nothing.
[logfile.txt](https://github.com/LeelaChessZero/lc0/files/4310916/logfile.txt)

Looks like LC0 needs to be loaded again and/or run and stop infinite analysis bevor starting a test suite.
This helps sometimes.

**Comment by mooskagh** [comment] 2020-03-10 20:05
The UCI host seems to be not UCI compiant (no `ucinewgame` and no `isready` after setting the position).
So what happens is the engine starts to load the network on `go infinite` command and while it's loading, it already receives `stop` command.

If still should return the move immediately after that (without starting the search) though, so there seem to be something working incorrectly.

But I'm not able to reproduce it.

**Comment by mooskagh** [comment] 2020-03-10 21:05
Could you try to produce the process dump when Lc0 is hanging? Here are the instructions how to do it:

How to produce process dump (only useful if you use official release for Windows downloaded from GitHub (<http://lc0.org/releases>)):

1. Download and unpack **ProcDump**: <https://docs.microsoft.com/en-us/sysinternals/downloads/procdump>
2. Reproduce hanging of Lc0.
3. While Lc0 is hanging, run:
`procdump64.exe -mm lc0.exe`  <- this will produce a short dump. Use it if your search was long, millions of nodes.
or
`procdump64.exe -ma lc0.exe` <- this will produce full dump. Useful if your search was short. For long searches it can easily be gigabytes in size.
4. It will create a file named `Lc0.exe_YYMMDD_HHMMSS.dmp` (current date and time instead of YYMMDD_HHMMSS). Attach it to an issue in GitHub or post some other way.

**Comment by borg323** [comment] 2020-03-10 22:14
I can reproduce it about 50% of the time. Bisecting leads to <https://github.com/LeelaChessZero/lc0/commit/3ff07fea993bca7eca972aeb3a70563a98728f9a>. The obvious candidate is setting the default for `--max-concurrent-searchers` to 1, and indeed setting `--max-concurrent-searchers=0` works fine.

**Comment by borg323** [comment] 2020-03-10 22:57
@Chess321 can you check if <https://ci.appveyor.com/api/buildjobs/lcrpc8o5wp3mdgtf/artifacts/build%2Flc0.exe> (#1123) fixes the issue?

**Comment by Chess321** [comment] 2020-03-11 17:46
@mooskagh 
I have the dmp file but I don't know how to post it here. Copy and paste doesn't work.

@borg323 
**Yes it fixes the issues.**

When I start the Fritz GUI first and run infinite analysis, LC0 is analysing.
It is also analysing when clicking infinite analysis on and off and on...
It is also analysing when running test suites.

**Comment by mooskagh** [comment] 2020-03-11 18:46
The v0.24.0 which was just released a few minutes ago, has this issue fixed.

Thanks for the bug report, we were closed to overlooking this bug.

Closing the issue as this is fixed.

**Closed by mooskagh** 2020-03-11 18:46 UTC
Labels: bug, release blocker
