### ISSUE TITLE
Implement resign in lc0

### ISSUE THREAD

**Issue by mooskagh** [LeelaChessZero/lc0#20] opened 2018-06-02 08:15 UTC
_From @mooskagh on May 27, 2018 16:13_

Resign is not yet implemented in lc0. Implement that.

_Copied from original issue: glinscott/leela-chess#674_

**Comment by mooskagh** [comment] 2018-06-02 09:40
Best done via adding `bool want_resign;` into `BestMoveInfo`

**Comment by gonzalezjo** [comment] 2018-06-05 19:45
Do we want cfg_min_resign_moves to be changeable from the command line? That wasn't the case in lczero, but the naming conventions suggest that it was intended.

**Comment by mooskagh** [comment] 2018-06-05 19:56
Why would we ever need to limit minimum number of moves before resign at all... I'd not implement this functionality unless there is justification.

As for resign threshold, that surely should be configurable.

**Comment by gonzalezjo** [comment] 2018-06-05 19:57
No idea, but it was in lczero. I'll leave that out, then.

**Comment by killerducky** [comment] 2018-06-05 20:00
Just for history: It was originally in LZGo so it doesn't instantly resign handicap games without at least trying. They later modified it with more stuff like scaled based on handicap stones.

**Comment by dubslow** [comment] 2018-06-14 01:00
Closed by #80, I believe.

**Closed by dubslow** 2018-06-14 01:00 UTC
Labels: good first issue
