### ISSUE TITLE
Crash in multiplexed setup with blas, opencl and heavy threading

### ISSUE THREAD

**Issue by frpays** [LeelaChessZero/lc0#98] opened 2018-06-19 20:40 UTC
The testing of PR https://github.com/LeelaChessZero/lc0/pull/87 did bring out a crash on MacOS (and MacOS only) under Multiplexed condition with OpenCL and BLAS, and heavy threading.

Only command line was causing the crash (between a few seconds and a few minutes) is the following:
``
./lc0 --backend=multiplexing "--backend-opts=a(backend=blas,threads=8),b(backend=opencl,threads=3)" -t 11 --minibatch-size=64
``

The crash was not happening every time immediately. You had to run up to 100k nodes (possibly in different runs) to experience it. Sometimes it went it in less a 1K nodes. But it was very replicable, but very random.

Today Gabby experienced same problem happened **on master**:

> Here's my crash with the latest master, run with ./lc0 weights.txt --backend=multiplexing '--backend-opts=a(backend=blas,threads=4),b(backend=opencl,threads=3)' -t 7 --minibatch-size=64. This is not using the PR. https://ghostbin.com/paste/5vxbg

[He] was also running the 256x20 net by @logosgg at the time

**Comment by frpays** [comment] 2018-06-19 20:47
This crash looks very similar to the problem encountered in testing PR87.  

The https://github.com/LeelaChessZero/lc0/pull/87

- If the problem are related, the PR87 makes it happen much more often.

- The problem happens ** only on MacOS **

- The problem happens both with vecLib or Mkl

Here are a few stack traces or the crash happening under PR87.

https://pastebin.com/2R224eaz
https://pastebin.com/ez9CPy7r
https://pastebin.com/3AQ6s0iz
https://pastebin.com/mGVPttHS
https://pastebin.com/3iJAnxcM 
https://pastebin.com/2DRQtUbt 
https://pastebin.com/1fRHzAAG 
https://pastebin.com/wFMzgT0F
https://pastebin.com/xTaVzXxM
https://pastebin.com/yMfYj7V1

**Comment by mooskagh** [comment] 2018-06-19 21:16
If someone wants to try to reproduce that on linux+clang+llvm stl (it's suspected to be llvm stl specific), here's what to do:

In meson.build, add:
```
  add_project_arguments('-stdlib=libc++', language : 'cpp')
...
  deps += [
    cc.find_library('c++'),
    cc.find_library('c++abi'),
    ]
```

Generate project like this:
```
CXX=clang++ CC=clang meson build/debugoptimized/ --buildtype debugoptimized -Dtf=false -Dcudnn=false
```

**Comment by mooskagh** [comment] 2018-06-19 21:21
And to check the PR locally:
```bash
git remote add upstream https://github.com/LeelaChessZero/lc0.git # if didn't do that before
git fetch upstream pull/87/head:BRANCHNAME # will create a new local branch BRANCHNAME and fetch PR into it
```

**Comment by frpays** [comment] 2018-06-19 21:23
A few information about this crash under PR https://github.com/LeelaChessZero/lc0/pull/87.

- It does crash also in debug
- It does not crash under Linux no matter what
- It does not crash if you swap opencl with random
- it does not crash if you swap blas with random
- it does not crash if you append `--nn-cache=0` 
- it does crash with MKL at the place of vecLib
- It does not crash with BLAS alone even heavily multi-threaded

**Comment by jnewlin12345** [comment] 2018-06-19 21:23
can you build on mac with -fsanitize=thead in the clang flags?

**Comment by GBeauregard** [comment] 2018-06-19 22:10
@jnewlin12345 https://ghostbin.com/paste/fsvg8 

This is with #87; I haven't reproduced a crash with the thread sanitizer yet though.

**Comment by GBeauregard** [comment] 2018-06-20 06:04
Here's a crash _with_ PR #87 merged into master, mkl, debug version, with thread sanitizer enabled.

Here's full commandline output:
https://ghostbin.com/paste/rdnow
Here's the crash dump:
https://ghostbin.com/paste/27r3j

**Comment by frpays** [comment] 2018-06-20 07:06
linux+clang+llvm: **no** crash under PR87 with  after 7.5 hour.

**Comment by frpays** [comment] 2018-06-20 07:36
PR87 + windows (visual C++ 2017): **no** crash (25 mn, 800k nodes).

**Comment by frpays** [comment] 2018-06-20 18:56
I reproduced the crash on MacOS, with current master (before recent #99) with MKL.

https://ghostbin.com/paste/zswqq  (sig11 )
https://ghostbin.com/paste/epxr9  (sig11)
https://ghostbin.com/paste/u4bcq  (assert failed)

**Comment by frpays** [comment] 2018-06-24 16:17
OpenCL is ruled out as a possible root cause.

` ./lc0 --backend=multiplexing "--backend-opts=a(backend=blas)" -t 11 --minibatch-size=64`, [that] works well for me everytime. (Bhāskara)

**Comment by GBeauregard** [comment] 2018-07-11 05:07
I'm having trouble reproducing this on current master. Can somebody else confirm?

**Comment by GBeauregard** [comment] 2018-07-14 20:52
Looks like I still get crashes but just harder for me to reproduce. Somebody else ( @frpays ? ) should try to reproduce on current master and see if the issue looks the same to them.

**Comment by frpays** [comment] 2018-07-15 17:20
Yes, as of d063d388a4beec451e1f5985db023368acf56e23, I can still reproduce it on MacOS.

```
./lc0 --backend=multiplexing "--backend-opts=a(backend=blas,threads=8),b(backend=opencl,threads=3)" -t 11 --minibatch-size=64
(...)

info depth 3 seldepth 8 time 2104 nodes 175 score cp 18 hashfull 1 nps 83 pv c2c4 c7c5 g1f3 g7g6 e2e4 f8g7 d2d4 c5d4
info depth 3 seldepth 9 time 2820 nodes 328 score cp 19 hashfull 1 nps 116 pv c2c4 c7c5 g1f3 g7g6 e2e4 f8g7 d2d4 c5d4
info depth 3 seldepth 10 time 3600 nodes 473 score cp 21 hashfull 2 nps 131 pv c2c4 c7c5 g1f3 e7e6 e2e4 b8c6 d2d4 c5d4 f3d4
Segmentation fault: 11

```

**Comment by frpays** [comment] 2018-07-15 18:33
Was able to reproduce it many time with:

```./lc0 --backend=multiplexing "--backend-opts=a(backend=blas,threads=8)" -t 11 --minibatch-size=64 ```

But not with

```
./lc0 --backend=blas  -t 11 --minibatch-size=64
````

Logically, with all the data gathered, the issue is triggered by the Mux backend.

**Comment by dubslow** [comment] 2018-07-16 00:55
@TheAnswer what os were you on?

**Comment by TheAnswer** [comment] 2018-07-16 06:53
@dubslow macOS High Sierra 10.13.6

**Comment by frpays** [comment] 2018-07-16 17:18
Sierra 10.12.6

**Comment by TheAnswer** [comment] 2018-09-12 07:35
I noticed a pattern of crashing inside notify_one in MuxingComputation::NotifyReady. Set up some traps in the object's dtor and confirmed that it was being destroyed during NotifyReady() execution. 

Can someone who can reproduce this please try my PR #348  and see if it fixes it for them.

I can't reproduce it anymore on MacOS with multiplexing blas MKL+ispc on a i7-7700HQ.

**Comment by oscardssmith** [comment] 2018-11-15 20:30
This has been fixed, right?

**Closed** 2019-01-02 19:49 UTC
Labels: bug, lc0
