### ISSUE TITLE
Lc0 terrible at chess endings

### ISSUE THREAD

**Issue by YouriAndropov** [LeelaChessZero/lc0#1084] opened 2020-02-18 12:14 UTC
It seems lc0 plays very bad when it comes to chess endings. Even with additional time per move in blitz, 2 or 3 seconds does not seem enough to find obvious checkmate. Eventually it finds a way, but after a big number of useless moves. Could it be a MCTS side effect ?

I'm using a 128x10 and a 256x20 network on a nvidia GTX 1080 Ti hardware. 

Ex: (lc0 plays white, timecontrol 300+2)

`1. d4 Nf6 2. c4 e6 3. Nf3 Be7 4. g3 d5 5. Bg2 O-O 6. O-O dxc4 7. Qc2 a6 8.
a4 Bd7 9. Qxc4 {+0.34/10 5} Bc6 {-0.12/22 12} 10. Bf4 {+0.32/10 9} Nd5
{0.00/23 14} 11. Bd2 {+0.45/10 5} Nd7 {0.00/23 19} 12. Re1 {+0.50/11 13} a5
{0.00/23 10} 13. e4 {+0.58/12 4} Nb4 {-0.15/23 13} 14. Qb3 {+0.58/12 5} b6
{-0.18/24 20} 15. Na3 {+0.58/12 6} Bb7 {-0.11/21 10} 16. Rad1 {+0.59/12 6}
h6 {-0.19/22 31} 17. h4 {+0.71/12 19} Kh8 {-0.07/22 25} 18. Bc3 {+0.75/10
16} Kg8 {-0.07/21 10} 19. Rd2 {+0.66/11 5} Rc8 {-0.06/21 3} 20. Nc4
{+0.90/11 8} Qe8 {-0.20/20 1} 21. Qd1 {+0.90/12 8} Na2 {-0.07/24 15} 22.
Qb1 {+0.89/12 6} Nxc3 {-0.07/23 4} 23. bxc3 {+0.88/12 0} Nf6 {-0.12/23 10}
24. Ra2 {+0.91/15 10} Ba6 {-0.12/23 6} 25. Bf1 {+1.00/11 21} Bb7 {-0.12/23
2} 26. Nce5 {+0.89/12 10} Ba8 {-0.29/21 10} 27. Rb2 {+1.16/11 10} Ba3
{-0.27/23 5} 28. Rb3 {+1.06/12 5} Bd6 {-0.33/23 4} 29. Bb5 {+1.78/16 5} Qe7
{-0.27/22 1} 30. Nc6 {+1.77/12 6} Bxc6 {-0.27/20 0} 31. Bxc6 {+1.78/12 4}
e5 {-0.28/22 1} 32. Kg2 {+1.76/11 20} Ng4 {-0.34/21 8} 33. Rb2 {+1.78/12 1}
Rcd8 {-0.36/21 9} 34. Rbe2 {+1.78/12 4} g6 {-0.42/21 12} 35. Qb5 {+1.90/11
10} Kh8 {-0.54/22 6} 36. h5 {+1.89/10 9} g5 {-0.66/22 5} 37. Rb1 {+1.91/9
17} Rg8 {-0.66/21 10} 38. Qc4 {+1.92/9 7} Rgf8 {-0.68/21 7} 39. Qb5
{+1.91/9 10} Rg8 {0.00/24 1} 40. Bd5 {+1.87/9 10} Rge8 {-0.59/21 6} 41. Qc4
{+1.92/9 6} Rf8 {-0.68/21 8} 42. Rb5 {+1.87/10 9} Kg7 {-0.50/20 3} 43. Bc6
{+1.89/10 6} Qe6 {-0.65/22 4} 44. Nd2 {+1.85/10 6} Qxc4 {-0.88/21 7} 45.
Nxc4 {+2.23/12 4} exd4 {-0.88/20 0} 46. cxd4 {+2.09/16 4} Bb4 {-1.04/22 2}
47. Ne3 {+2.09/19 4} Nxe3+ {-0.67/23 1} 48. fxe3 {+2.06/16 1} Rd6 {-0.67/24
0} 49. Rc2 {+2.49/10 9} f6 {-0.60/24 2} 50. Rf5 {+2.37/10 16} Rf7 {-0.56/23
1} 51. Kf2 {+2.29/11 7} Re7 {-0.56/25 1} 52. Ke2 {+2.25/11 2} Ree6
{-0.56/26 4} 53. Bd5 {+2.22/11 2} Re7 {-0.56/24 0} 54. Bc6 {+2.16/11 6}
Ree6 {0.00/29 1} 55. Bd5 {+2.14/11 1} Re7 {0.00/31 1} 56. Kd3 {+2.09/10 8}
Be1 {-0.56/25 3} 57. g4 {+2.32/9 3} Bb4 {-0.56/25 1} 58. Bc6 {+2.25/9 3}
Rd8 {-0.61/25 8} 59. Rf1 {+2.42/8 5} Rd6 {-0.56/25 1} 60. Rff2 {+2.36/8 4}
Bc5 {-0.56/25 0} 61. Bd5 {+2.29/9 1} Bb4 {-0.56/26 1} 62. Bc6 {+2.24/9 3}
Bc5 {0.00/28 1} 63. Bd5 {+2.23/9 2} Bb4 {0.00/28 0} 64. Rf1 {+2.11/9 5}
Red7 {-0.56/25 1} 65. Bc6 {+2.24/8 2} Re7 {0.00/30 0} 66. Rc4 {+2.25/8 2}
Rd8 {-0.56/27 4} 67. Rcc1 {+2.26/7 3} Rd6 {-0.56/29 5} 68. Rc2 {+2.25/8 1}
Ba3 {-0.61/28 15} 69. Rc4 {+2.22/8 3} Bc5 {-0.56/26 1} 70. Bd5 {+2.25/9 1}
Bb4 {-0.56/24 1} 71. Rc2 {+2.14/8 3} Red7 {0.00/29 1} 72. Rf5 {+2.16/8 2}
Re7 {0.00/31 1} 73. Rff2 {+2.16/8 2} Red7 {-0.61/26 1} 74. Rf1 {+2.15/8 2}
Re7 {-0.61/27 2} 75. Rc4 {+2.17/8 2} c5 {-0.56/25 4} 76. Rf2 {+2.04/8 2}
Kf8 {-0.55/25 3} 77. Rcc2 {+2.01/8 1} Rc7 {-0.55/24 1} 78. Bc4 {+2.02/9 2}
Kg7 {-0.56/23 0} 79. Bd5 {+2.00/8 2} Kf8 {0.00/28 1} 80. Bc4 {+1.99/9 2}
Kg7 {0.00/26 0} 81. e5 {+1.96/11 1} fxe5 {-0.51/26 3} 82. d5 {+1.92/12 0}
Rf7 {-0.52/27 1} 83. Ke4 {+1.91/11 1} Be1 {-0.52/28 4} 84. Rfe2 {+1.93/10
1} Bb4 {-0.51/27 4} 85. Rf2 {+1.83/11 4} Be1 {0.00/30 0} 86. Rxf7+
{+1.83/13 0} Kxf7 {-0.48/27 1} 87. Rc1 {+1.85/12 0} Bb4 {-0.48/28 1} 88.
Rf1+ {+1.81/10 3} Ke7 {-0.48/26 0} 89. Rf5 {+1.79/12 3} Bc3 {-0.48/28 1}
90. Kd3 {+1.78/11 0} Ba1 {-0.48/26 0} 91. Rf1 {+1.78/10 2} e4+ {-0.48/26 1}
92. Kxe4 {+1.76/9 0} Bg7 {-0.48/27 1} 93. Bb5 {+1.72/9 3} Rd8 {-0.48/26 3}
94. Rb1 {+1.70/8 2} Bc3 {-0.48/26 1} 95. Rf1 {+1.63/9 2} Bg7 {0.00/33 0}
96. Rf5 {+1.60/9 1} Bf6 {-0.48/28 4} 97. Kd3 {+1.63/9 1} Rd6 {-0.48/28 3}
98. Ba6 {+1.62/9 1} Bb2 {-0.48/26 1} 99. Bc4 {+1.60/9 2} Bg7 {-0.48/26 0}
100. Ba2 {+1.59/9 1} Rd8 {-0.53/26 4} 101. Kc4 {+1.72/10 1} Kd6 {-0.75/25
4} 102. Kb5 {+2.03/10 1} c4 {-0.76/24 2} 103. Bxc4 {+2.00/10 2} Rc8
{-0.76/25 1} 104. Bf1 {+2.11/10 1} Rf8 {-0.92/26 11} 105. Rxf8 {+2.86/11 1}
Bxf8 {-1.37/26 3} 106. Kxb6 {+2.95/12 1} Kxd5 {-1.37/25 0} 107. Kxa5
{+2.98/11 1} Bc5 {-2.00/26 9} 108. Bg2+ {+3.03/11 1} Kc4 {-1.92/24 0} 109.
e4 {+3.85/9 2} Bd4 {-3.73/26 7} 110. Ka6 {+4.06/9 2} Kc5 {-4.62/24 2} 111.
Kb7 {+4.44/8 2} Bc3 {-4.62/25 0} 112. Kc7 {+4.64/8 2} Ba5+ {-4.62/25 2}
113. Kd7 {+5.83/8 1} Kd4 {-4.62/24 0} 114. Ke6 {+5.72/8 3} Be1 {-8.11/21 3}
115. Kf5 {+6.53/7 3} Kc5 {-9.71/26 5} 116. Kg6 {+7.79/7 2} Bc3 {-9.99/21 4}
117. Kxh6 {+10.37/6 1} Kd4 {-12.54/20 4} 118. Kxg5 {+12.16/6 2} Ke5
{-15.65/19 3} 119. h6 {+12.82/6 2} Bd2+ {-17.06/19 3} 120. Kh5 {+13.88/6 1}
Bc3 {-17.71/19 2} 121. h7 {+14.31/6 2} Kf4 {-16.98/17 0} 122. Kg6 {+16.86/6
2} Bh8 {-23.51/18 3} 123. Kf7 {+18.89/6 2} Ke3 {-117.05/17 2} 124. Kg8
{+20.76/6 1} Bd4 {-120.36/18 2} 125. h8=Q {+21.34/6 1} Kd3 {-119.23/16}
126. Qxd4+ {+85.47/5 1} Kxd4 {-M12/25 2} 127. Kh8 {+128.00/2 2} Ke3
{-M11/27 2} 128. Bh3 {+128.00/2 2} Kf4 {-M11/24 2} 129. g5 {+128.00/2 1}
Kxg5 {-M11/28 2} 130. e5 {+128.00/2 2} Kh5 {-M10/29 2} 131. a5 {+128.00/2
1} Kg5 {-M9/29 2} 132. e6 {+128.00/2 2} Kf6 {-M8/30 1} 133. e7 {+128.00/2
1} Kxe7 {-M9/29 1} 134. a6 {+128.00/2 1} Kf6 {-M9/31 2} 135. a7 {+128.00/2
2} Ke5 {-M8/33 2} 136. Kg8 {+128.00/2 2} Kd4 {-M8/32 2} 137. Kf8 {+128.00/2
1} Kc4 {-M7/31 1} 138. Kg7 {+128.00/2 1} Kc5 {-M7/32 1} 139. a8=R
{+128.00/2 1} Kd4 {-M10/27 2} 140. Kg8 {+92.89/5 2} Ke3 {-M10/30 2} 141.
Rb8 {+74.06/5 1} Kd2 {-M10/32 2} 142. Kf7 {+61.49/5 1} Kc1 {-M9/31 2} 143.
Rb4 {+42.47/6 1} Kc2 {-M9/32 1} 144. Rf4 {+53.02/5 2} Kd3 {-M8/34 2} 145.
Rf6 {+36.54/5 1} Ke3 {-M8/35 1} 146. Rc6 {+43.31/5 1} Kd3 {-M8/35 1} 147.
Rc7 {+39.38/5 2} Kd4 {-M8/36 1} 148. Rb7 {+38.15/6 1} Kd5 {-M8/37 1} 149.
Rb2 {+37.51/5 2} Kd4 {-M8/37 2} 150. Bc8 {+35.75/5 1} Ke3 {-M8/37 2} 151.
Rh2 {+31.27/5 2} Kf4 {-M8/39 1} 152. Rh8 {+27.54/5 1} Ke3 {-M8/39 2} 153.
Ke8 {+23.42/5 1} Kd4 {-M8/38 1} 154. Rh6 {+23.51/5 2} Ke5 {-M8/39 2} 155.
Bf5 {+19.15/6 1} Kxf5 {-M9/36 2} 156. Rh2 {+42.40/6 2} Ke4 {-M9/39 2} 157.
Kf8 {+51.94/6 1} Kd3 {-M9/41 1} 158. Kg7 {+48.02/6 1} Ke3 {-M9/43 1} 159.
Rh5 {+39.00/6 1} Kd2 {-M9/46 1} 160. Rf5 {+40.19/6 1} Kc3 {-M9/49 2} 161.
Kf7 {+32.31/6 1} Kc2 {-M8/50 2} 162. Rg5 {+31.93/6 2} Kd3 {-M9/50 1} 163.
Rg8 {+35.42/6 1} Kd4 {-M9/51 2} 164. Ra8 {+29.94/6 2} Kd3 {-M9/52 1} 165.
Ke8 {+25.00/6 1} Kc4 {-M9/49 1} 166. Ra7 {+21.67/6 1} Kd4 {-M9/55 2} 167.
Rg7 {+22.54/6 2} Ke4 {-M9/56 1} 168. Rg1 {+16.84/6 1} Kd4 {-M9/58 2} 169.
Kd7 {+15.88/6 1} Ke5 {-M9/57 2} 170. Kc8 {+16.83/6 1} Kd5 {-M9/35 2} 171.
Kb7 {+16.11/6 2} Ke5 {-M9/53 1} 172. Ra1 {+16.43/6 2} Kf4 {-M9/57 1} 173.
Ka7 {+13.20/6 1} Ke4 {-M9/45 1} 174. Rb1 {+12.91/6 1} Kf3 {-M9/58 1} 175.
Rb5 {+11.63/6 1} Kg3 {-M9/61 1} 176. Kb8 {+9.95/6 1} Kh3 {-M8/64 1} 177.
Rb6 {+9.06/6 2} Kg4 {-M9/63 1} 178. Kc8 {+9.63/6 1} Kf5 {-M9/53 1} 179. Rb2
{+9.91/6 1} Ke6 {-M8/66 1} 180. Kb8 {+9.92/6 1} Kd6 {-M8/71 2} 181. Ka8
{+9.54/6 2} Kd5 {-M8/71 1} 182. Rh2 {+9.73/6 1} Kc5 {-M9/53 0} 183. Ka7
{+9.23/6 1} Kd5 {-M8/69 1} 184. Rh1 {+8.95/6 2} Ke4 {-M8/72 2} 185. Kb8
{+9.25/6 1} Ke5 {-M8/74 2} 186. Rh3 {+8.93/6 1} Kf4 {-M8/71 1} 187. Rh7
{+8.04/6 2} Kg3 {-M8/77 1} 188. Re7 {+7.69/6 2} Kf2 {-M8/59 2} 189. Kc7
{+7.07/6 1} Kf3 {-M8/76 2} 190. Kd6 {+7.56/6 2} Kf4 {-M8/75 1} 191. Re1
{+8.18/6 1} Kg4 {-M8/74 0} 192. Ke5 {+9.05/6 1} Kg3 {-M8/71 2} 193. Rf1
{+8.94/6 2} Kg2 {-M8/56 2} 194. Rf4 {+9.20/7 1} Kh3 {-M5/77 1} 195. Kf5
{+8.97/7 2} Kh2 {-M5/81 2} 196. Kg4 {+22.32/6 1} Kg2 {-M4/100 0} 197. Rf5
{+128.00/4 2} Kh2 {-M3/100 0} 198. Kf3 {+128.00/3 2} Kh1 {-M2/100 0} 199.
Rc5 {+128.00/2 2} Kh2 {-M2/100 0} 200. Rd5 {+128.00/2 1} Kg1 {-M2/100 0}
201. Ra5 {+128.00/2 2} Kh2 {-M2/100 0} 202. Rc5 {+128.00/2 1} Kg1 {-M2/100
0} 203. Kg3 {+128.00/2 2} Kf1 {-M2/100 0} 204. Re5 {+128.00/2 0} Kg1
{-M1/100 0} 205. Re1# {+128.00/2 1} 1-0`

**Comment by Naphthalin** [comment] 2020-02-18 13:31
> Could it be a MCTS side effect ?

Yes, exactly. The search is based on Q differences, which become arbitrarily small when the game is nearly decided, and is usually made more efficient by the policies favoring good moves, which suffer from the same problem. There is right now work on several possible solutions, see e.g. #961

**Comment by YouriAndropov** [comment] 2020-02-18 13:45
Couldn't you switch to a regular alpha-beta search when the game is nearly over ?

**Comment by mooskagh** [comment] 2020-02-18 14:17
Leela is trained to win, there's no incentive to try to do that faster.
So as long as this doesn't lead to dropping the win, that's working as intended.

We could try to give fast wins more score during training, but DeepMind said they tried it and while that reduced game duration, it reduced overall strength.


The similar issue exists in Go. People generally try to win by higher margin, but as it's a win regardless of the score, AlphaZero Go (and Leela Zero) usually wins just by one point. Some people may find that unaesthetic, but win is a win.

**Comment by YouriAndropov** [comment] 2020-02-18 14:37
In regular blitz games with no additional time, this causes lc0 to loose games with a winning position. It isn't just "aesthetic".

**Comment by mooskagh** [comment] 2020-02-18 15:18
Then we have to think how to properly model the probability of losing the game during the training.

Currently the ability to loss due to taking too many moves is not encoded in Leela's understanding of chess rules in any way.
it's tricky to add because training games are fixed nodes, and there's no time budgeting going on, and it's hard to address that.

But that will take some of network capacity and likely will reduce overall strength.

**Comment by ddobbelaere** [comment] 2020-02-18 16:39
TBH I don't really care about the problem in the zero-increment case, as every engine becomes terrible / times out in the limit for thinking time going to zero. However, a remedy for the underlying problem of unnecessarily prolonging the game is useful for all time controls (because of the higher implied average thinking time per move).

As @Naphthalin already mentioned, the most notable already investigated MCTS enhancement in this regard is #961 by @Ttl, which reduces the expected number of game plies considerably (factor 2 by the looks of it).

**Comment by YouriAndropov** [comment] 2020-02-18 18:16
Ok I'm eager to see this improvement.

> every engine becomes terrible / times out in the limit for thinking time going to zero

Nevertheless, MCTS seems much more sensitive to "zeitnot" than alpha-beta search.

**Comment by YouriAndropov** [comment] 2020-02-19 13:07
I did a few tests with 0.23.3 and yet I couldn't see any progress. Should I use a specific network with it ? Has the whole "moves left head" feature been merged ?

Ex: lc0 plays white, timecontrol 300+2. At ply 127, blacks are to be checkmated in 18 plies. At ply 150, lc0 promotes a queen, its a KKQ ending, the other (αβ) engine can still be checkmated in 8 plies, but checkmate is done at ply 199.
`1. e4 c5 2. Ne2 d6 3. d4 cxd4 4. Nxd4 Nf6 5. Nc3 a6 6. Be2 e6 7. Be3 Be7 8.
f4 {+0.60/11 8} O-O {-0.15/22 33} 9. g4 {+0.68/13 5} d5 {-0.02/23 17} 10.
e5 {+0.63/14 6} Nfd7 {+0.02/23 4} 11. Qd2 {+0.64/12 15} Bh4+ {0.00/23 11}
12. Kf1 {+0.67/11 6} Be7 {+0.20/22 11} 13. g5 {+0.62/12 14} b5 {+0.23/22
16} 14. Bd3 {+0.64/10 6} Bb7 {+0.53/20 13} 15. Qf2 {+0.60/11 7} Qc7
{+0.65/20 14} 16. Qh4 {+1.19/12 8} g6 {+0.46/19 4} 17. Qg3 {+1.31/13 3} Nc6
{+0.30/18 11} 18. h4 {+1.30/15 4} Nxd4 {+0.18/19 10} 19. Bxd4 {+1.50/11 9}
Bb4 {+0.08/20 9} 20. h5 {+1.88/11 13} Rae8 {0.00/20 6} 21. Ne2 {+2.14/10
17} Re7 {-0.11/22 21} 22. c3 {+2.45/8 5} Bc5 {-0.13/21 8} 23. Qh3 {+2.13/9
12} Bb6 {-0.15/21 7} 24. b4 {+2.25/9 5} Bxd4 {+0.01/19 2} 25. cxd4 {+2.69/9
5} Nb6 {0.00/20 2} 26. a3 {+2.49/9 15} Nc4 {0.00/20 6} 27. Kg2 {+2.44/9 8}
a5 {-0.31/20 9} 28. Rac1 {+2.29/9 8} a4 {+0.14/20 17} 29. Rh2 {+3.06/7 9}
Bc6 {+0.14/18 0} 30. Rc3 {+2.86/8 9} Be8 {+0.10/21 5} 31. Kf2 {+2.69/7 8}
Qb7 {+0.16/22 8} 32. Ke1 {+2.58/8 6} Qa7 {+0.16/22 3} 33. Bb1 {+2.62/8 8}
Qb8 {+0.16/21 3} 34. Rh1 {+2.72/7 10} Qc7 {+0.16/23 4} 35. Kf2 {+2.85/7 9}
Qa7 {+0.16/23 3} 36. Ke1 {+2.67/8 8} Qb7 {+0.16/24 5} 37. Nc1 {+2.70/7 9}
Qb6 {+0.16/24 4} 38. Ne2 {+2.57/8 3} Ra7 {+0.16/24 7} 39. Qh2 {+2.61/8 13}
Rd7 {+0.16/24 4} 40. Rh3 {+2.75/7 6} Qb7 {0.00/22 8} 41. Rd3 {+2.55/8 8}
Rc7 {+0.16/23 2} 42. Qh3 {+2.42/8 8} Re7 {+0.16/24 3} 43. Kf2 {+2.59/8 7}
Qc6 {+0.16/21 3} 44. Qh4 {+2.67/7 7} Qc8 {+0.16/22 2} 45. Kg2 {+2.51/7 7}
Rb7 {0.00/21 13} 46. Qh2 {+2.52/7 6} Rc7 {0.00/20 3} 47. Rh3 {+2.40/8 4}
Qb7 {0.00/21 2} 48. Rd1 {+2.31/9 5} Qb6 {+0.16/23 3} 49. Kf2 {+2.29/8 9}
Re7 {+0.16/23 3} 50. Rh1 {+2.52/7 3} Qa7 {+0.16/22 1} 51. Rd3 {+2.46/8 5}
Rc7 {+0.16/22 8} 52. Qh3 {+2.39/8 6} Qb6 {0.00/21 7} 53. Qh2 {+2.36/7 4}
Qc6 {+0.16/22 2} 54. Rh3 {+2.37/7 5} Qb7 {+0.16/22 1} 55. Rd3 {+2.22/8 3}
Qb6 {0.00/20 3} 56. Kg2 {+2.34/7 4} Qa7 {0.00/21 2} 57. Qh3 {+2.31/8 5} Re7
{0.00/22 2} 58. Rh2 {+2.45/7 3} Bc6 {0.00/21 12} 59. Rc3 {+2.57/7 2} Be8
{0.00/22 1} 60. Rh1 {+2.36/7 4} Kh8 {0.00/22 3} 61. Qh4 {+2.21/7 3} Kg8
{-0.12/22 10} 62. Rd3 {+2.43/7 2} Nb2 {0.00/22 1} 63. Rdh3 {+2.49/7 2} Nc4
{-0.15/21 3} 64. Qe1 {+2.33/7 3} Rc7 {0.00/20 2} 65. R1h2 {+2.16/7 2} Rb7
{0.00/22 2} 66. Qg1 {+2.26/7 2} Re7 {0.00/23 2} 67. Qf2 {+2.23/7 2} Qb7
{0.00/22 1} 68. Rh1 {+2.19/7 2} Qc8 {-0.08/21 2} 69. Qh4 {+2.12/7 2} Qb7
{0.00/23 1} 70. Qg4 {+2.01/7 2} Qc6 {0.00/23 2} 71. Bd3 {+1.93/7 2} Nxa3
{+0.58/18 2} 72. Qh4 {+1.72/7 2} Qd7 {+0.72/19 3} 73. Ra1 {+1.89/6 1} Nc4
{+1.20/17 0} 74. Qf2 {+1.72/7 1} Qd8 {+0.70/17 4} 75. Ng1 {+1.80/8 2} Ra7
{+0.29/15 3} 76. Nf3 {+1.75/9 1} Qe7 {0.00/16 2} 77. Qe1 {+1.91/9 1} Nb2
{+0.43/15 2} 78. Bb1 {+1.89/11 1} Nc4 {-0.23/18 2} 79. Nh2 {+2.19/9 2} Kg7
{-0.25/19 3} 80. Ng4 {+2.06/8 2} Rh8 {-0.23/18 1} 81. Nf6 {+1.92/9 2} Kf8
{-0.35/17 2} 82. Ra2 {+1.84/8 2} Qc7 {-0.33/16 2} 83. hxg6 {+1.80/8 1} fxg6
{-0.32/16 0} 84. Rh6 {+1.71/8 1} Qb6 {-0.26/18 3} 85. Qg1 {+1.58/10 1} Rg7
{-0.16/18 1} 86. Kg3 {+1.47/9 1} Qa7 {-0.14/18 0} 87. Rah2 {+1.38/10 1} a3
{0.00/18 1} 88. Ba2 {+1.36/12 1} Rc7 {0.00/19 2} 89. Kg4 {+0.99/11 2} Qa4
{0.00/19 0} 90. Qe1 {+0.83/12 1} Qa7 {0.00/21 2} 91. Qf2 {+0.69/12 2} Qa4
{0.00/18 2} 92. Qe1 {+0.66/13 0} Qa7 {0.00/20 0} 93. Qf2 {+0.57/12 4} Qa4
{0.00/20 0} 94. Qf3 {+0.53/14 0} Bf7 {0.00/18 0} 95. Nxh7+ {+0.70/9 2} Ke7
{0.00/20 2} 96. Nf6 {+0.64/11 1} Rf8 {0.00/20 4} 97. R6h3 {+0.51/10 3} Ra7
{0.00/19 2} 98. Qb3 {+0.81/8 2} Qxb3 {+0.16/19 0} 99. Rxb3 {+0.65/10 0} Kd8
{+0.14/22 1} 100. Rh7 {+1.22/8 1} Kc7 {+0.14/21 0} 101. Rbh3 {+1.09/10 2}
Kc6 {+0.11/18 0} 102. Rg7 {+1.53/10 1} Rc8 {-0.48/20 6} 103. Kf3 {+1.26/11
3} Rcc7 {-0.68/19 5} 104. f5 {+1.40/8 1} exf5 {-0.84/19 2} 105. Rh6
{+1.40/9 1} Kb7 {-0.93/19 2} 106. Kf4 {+1.47/9 1} Nb6 {-0.96/20 3} 107. Rh8
{+1.67/11 1} Ka6 {-0.97/20 2} 108. Rhh7 {+1.71/10 1} Re7 {-0.97/15 0} 109.
Rh3 {+1.81/14 2} Nc4 {-0.97/16} 110. Bxc4 {+1.93/17 1} bxc4 {-2.57/19 4}
111. Rxa3+ {+1.99/16 1} Kb6 {-3.10/20 3} 112. Rxf7 {+2.10/15 1} Rxf7
{-1.14/19 2} 113. e6 {+2.14/14 0} Rfb7 {-1.92/20 3} 114. Rxa7 {+2.34/14 2}
Kxa7 {-1.80/18} 115. Nxd5 {+2.62/11 2} Rb8 {-2.68/19 3} 116. Ke5 {+2.73/10
2} Ka6 {-3.02/19 2} 117. e7 {+2.93/9 3} Kb5 {-2.68/17 1} 118. Ke6 {+3.10/9
1} Ka4 {-4.31/18 2} 119. Kf7 {+3.50/9 2} f4 {-3.08/16 0} 120. Nxf4 {+4.94/8
1} Rb7 {-8.57/17 3} 121. Kf8 {+5.75/7 4} Rb8+ {-10.91/15 2} 122. e8=Q+
{+6.96/8 1} Rxe8+ {-10.91/14 0} 123. Kxe8 {+7.46/8 1} Kxb4 {-13.33/19 3}
124. d5 {+128.00/2 3} Kc5 {-17.78/17 2} 125. Ke7 {+128.00/2 1} Kd4
{-14.98/15} 126. d6 {+128.00/2 2} Ke4 {-30.00/17 3} 127. Ne2 {+128.00/2 2}
Kf3 {-M18/19 2} 128. Kf6 {+128.00/3 2} Kxe2 {-M18/23 2} 129. d7 {+128.00/1
1} c3 {-M14/28 1} 130. d8=Q {+128.00/1 1} c2 {-M14/28 0} 131. Qc7
{+128.00/2 2} Kd1 {-M13/28 1} 132. Qd6+ {+128.00/2 2} Kc1 {-M13/28 2} 133.
Qc5 {+128.00/2 1} Kd1 {-M13/28 3} 134. Qg1+ {+128.00/2 1} Kd2 {-M13/29 1}
135. Qf2+ {+128.00/2 1} Kd1 {-M13/29 0} 136. Qf1+ {+128.00/2 1} Kd2
{-M13/30 1} 137. Qf4+ {+128.00/2 2} Kd1 {-M13/20 3} 138. Qa4 {+128.00/2 1}
Kd2 {-M13/31 1} 139. Qa2 {+128.00/2 2} Kd1 {-M12/32 1} 140. Qa4 {+128.00/2
2} Kd2 {0.00/36 0} 141. Kxg6 {+128.00/2 1} c1=Q {-M12/31 4} 142. Qf4+
{+128.00/2 1} Kd1 {-M12/32 0} 143. Qxc1+ {+128.00/2 2} Kxc1 {-M10/35 2}
144. Kg7 {+128.00/2 2} Kd1 {-M10/37 1} 145. Kh8 {+128.00/2 2} Kd2 {-M10/40
1} 146. g6 {+128.00/2 1} Kd3 {-M10/38 0} 147. g7 {+128.00/2 1} Ke4 {-M8/38
4} 148. Kh7 {+128.00/2 1} Ke3 {-M8/38 1} 149. Kg6 {+128.00/2 2} Ke4 {-M8/37
1} 150. g8=Q {+128.00/2 1} Kd4 {-M7/37 2} 151. Qd8+ {+54.92/6 2} Kc4
{-M6/39 3} 152. Kh7 {+60.40/6 1} Kc5 {-M6/42 2} 153. Qe8 {+40.11/6 2} Kd5
{-M6/44 1} 154. Kg7 {+41.09/6 1} Kd4 {-M6/45 1} 155. Qg6 {+40.17/6 1} Kc5
{-M6/46 1} 156. Kh8 {+37.52/6 2} Kd5 {-M6/49 1} 157. Qg2+ {+33.69/6 1} Kc5
{-M6/50 1} 158. Kh7 {+28.84/6 1} Kd6 {-M6/50 1} 159. Qf3 {+30.80/6 1} Kc7
{-M6/51 2} 160. Kg6 {+24.19/6 1} Kb6 {-M6/51 1} 161. Kh5 {+22.69/6 2} Kb5
{-M6/50 1} 162. Qb7+ {+20.25/6 2} Kc5 {-M6/50 0} 163. Qb1 {+17.70/6 1} Kc6
{-M6/53 1} 164. Kh6 {+18.64/6 1} Kc5 {-M6/44 0} 165. Qe1 {+18.79/6 2} Kd4
{-M6/53 1} 166. Qf2+ {+16.94/6 1} Kc4 {-M6/54 2} 167. Kg7 {+16.97/6 1} Kb5
{-M6/55 1} 168. Kf8 {+15.49/6 2} Kc6 {-M6/54 1} 169. Qe2 {+14.09/6 1} Kc5
{-M6/55 1} 170. Kg8 {+14.79/6 1} Kc6 {-M6/55 1} 171. Qe6+ {+12.74/6 1} Kb5
{-M6/57 1} 172. Kh7 {+12.53/6 1} Kc5 {-M6/58 1} 173. Qh3 {+12.02/6 1} Kd4
{-M6/59 2} 174. Kg8 {+11.97/6 1} Kc5 {-M6/59 2} 175. Kf8 {+11.88/6 2} Kc6
{-M6/57 5} 176. Qh7 {+11.11/6 1} Kb6 {-M6/58 4} 177. Kg7 {+10.36/6 2} Kc6
{-M6/58 1} 178. Kg6 {+10.30/6 2} Kd5 {-M6/58 2} 179. Qa7 {+10.47/6 2} Kc4
{-M6/58 1} 180. Kf7 {+11.49/6 1} Kb5 {-M6/57 2} 181. Qb8+ {+10.51/6 1} Kc4
{-M6/59 1} 182. Kf8 {+11.51/6 1} Kc5 {-M6/58 3} 183. Qb1 {+10.84/6 1} Kc4
{-M6/58 3} 184. Kg8 {+11.29/6 2} Kc5 {-M5/60 2} 185. Qh7 {+10.69/6 1} Kc6
{-M5/59 2} 186. Qc2+ {+10.01/6 1} Kb5 {-M6/40 0} 187. Qg6 {+10.55/6 2} Kc4
{-M6/59 1} 188. Qh5 {+11.82/6 1} Kb3 {-M6/59 3} 189. Kf7 {+12.66/6 1} Kc4
{-M6/40 0} 190. Ke6 {+13.32/6 2} Kd4 {-M6/47 0} 191. Qd1+ {+13.55/6 1} Kc4
{-M6/49 0} 192. Ke5 {+12.43/6 1} Kb5 {-M5/56 1} 193. Kd5 {+13.45/6 2} Kb6
{-M4/60 1} 194. Qb3+ {+128.00/5 2} Kc7 {-M3/66 1} 195. Qb5 {+128.00/2 1}
Kc8 {-M2/65 4} 196. Kd6 {+128.00/2 1} Kd8 {-M1/128 0} 197. Qa4 {+128.00/2
2} Kc8 {-M1/98 0} 198. Qb5 {+128.00/2 1} Kd8 {0.00/101 0} 199. Qd7#
{+128.00/2 1} 1-0`

**Comment by Ipmanchess** [comment] 2020-02-19 13:34
Hi Youri..are you also on Lc0 discord..if yes ,with what name..else you can contact me at ipmanchess

**Comment by Naphthalin** [comment] 2020-02-19 14:25
> I did a few tests with 0.23.3 and yet I couldn't see any progress.

The bug fix was only for a specific time management bug where the nps calculation started at the wrong time.

> Should I use a specific network with it ? Has the whole "moves left head" feature been merged ?

Not merged yet (as you see in the #961 PR), and the only net I am aware of is a net which got its MLH trained afterwards, so it didn't influence the policies directly.

**Comment by YouriAndropov** [comment] 2020-02-19 19:05
When there's a testable binary available, please let me know (I use the cuda fp32 backend), if it helps.

**Comment by Naphthalin** [comment] 2020-05-01 11:40
@YouriAndropov we have released v0.25.1, please try it together with a suitable network like 712576 from http://training.lczero.org/networks/?show_all=1 and the moves-left-head settings for run 3 on http://training.lczero.org/training_runs

**Comment by mooskagh** [comment] 2020-05-03 07:33
Let's move all the shuffling discussion to #1229 for now.

Closing this as duplicate. Feel free to reopen if you think it's different.

**Closed by mooskagh** 2020-05-03 07:33 UTC
