### ISSUE TITLE
v0.19.0-dev master doing nonsense moves?

### ISSUE THREAD

**Issue by nblaxall** [LeelaChessZero/lc0#464] opened 2018-10-26 11:36 UTC
In the ccc2 Blitz battle game 1579 Boot vs Lc0 (dated 2018.10.25) after move 13. exd6 we have fen 2rq1rk1/1p2bppp/p1bPp3/2p5/P4Bn1/2NP1N2/1PP1QPPP/R3R1K1 b - - 0 13 ... and lc0 v0.18.1 takes the pawn back 13...Bxd6 or doing 13...Bf6 (both sensible moves).
SF also wants to do 13...Bxd6.

v0.19.0-dev master (with full game history) at first wants to do 13...Bxd6 but after 15516 nodes it wants to do 13...Nf6 and sac the bishop.
This is a bad move, and SF says it's giving up the bishop for no compensation, jumping from about even to about +5 for white (Depth 33/53).

Pastebin of v0.18.1 search: https://pastebin.com/S7JH2DjJ
Pastebin of v0.19.0-dev master search: https://pastebin.com/c3uqQaGa

PGN of the game:
[Event "CCC 2: Blitz Battle (5|2)"]
[Site "Chess.com"]
[Date "2018.10.25"]
[Round "?"]
[White "Booot 6.3.1"]
[Black "Lc0 0.18.1"]
[Result "1/2-1/2"]
[BlackElo "2000"]
[ECO "B51"]
[Opening "Sicilian"]
[Time "18:29:07"]
[Variation "3.Bb5+ Nd7"]
[WhiteElo "3276"]
[TimeControl "300+2"]
[Termination "normal"]
[PlyCount "72"]
[WhiteType "program"]
[BlackType "program"]

1. e4 c5 2. Nf3 d6 3. Bb5+ Nd7 4. a4 Nf6 5. Nc3 a6 6. Bxd7+ Bxd7 7. O-O e6 8. Re1 Rc8 9. d3 Bc6 10. Bf4 Be7 11. Qe2 O-O 12. e5 Ng4 13. exd6 Bxd6 14. Bxd6 Qxd6 15. Ne4 Qc7 16. a5 c4 17. dxc4 Bxe4 18. Qxe4 Nf6 19. Qe2 Qxc4 20. Qxc4 Rxc4 21. c3 Rd8 22. Ne5 Rcc8 23. Red1 Kf8 24. Rxd8+ Rxd8 25. Kf1 Rd5 26. Nc4 Ke7 27. Nb6 Rf5 28. Ra4 Rb5 29. Rc4 Rxb2 30. Rc7+ Ke8 31. Rxb7 Ra2 32. Rb8+ Ke7 33. Rb7+ Kf8 34. Rb8+ Ke7 35. Rb7+ Ke8 36. Rb8+ Ke7 1/2-1/2

**Comment by nblaxall** [comment] 2018-10-26 11:54
I should mention I cloned v0.19.0-dev master by doing:
$ git clone -b master --recurse-submodules https://github.com/jjoshua2/lc0.git
... I hope that's correct as I'm a newbie at git.

**Comment by mooskagh** [comment] 2018-10-26 11:56
Could you try:
```bash
$ git clone -b master --recurse-submodules https://github.com/LeelaChessZero/lc0.git
```
?

**Comment by nblaxall** [comment] 2018-10-26 12:11
I have now done:
$ git clone -b master --recurse-submodules https://github.com/LeelaChessZero/lc0.git
but it still has the problem: https://pastebin.com/a3uv2jsF

**Comment by mooskagh** [comment] 2018-10-26 12:13
Could you also add `--verbose-move-stats` ?

**Comment by mooskagh** [comment] 2018-10-26 12:48
Thanks! Something is clearly wrong with V. I should have time in the evening to take a look.

**Comment by Ttl** [comment] 2018-10-26 13:57
It looks like you are on Mac. At Leela Zero Go version we have had many reports that some Apple devices have broken OpenCL drivers that give incorrect results. Unfortunately only Apple can fix the broken drivers, but they have deprecated OpenCL in favour of their own Metal API so it's unlikely to ever be fixed.

**Comment by mooskagh** [comment] 2018-10-26 13:58
It's weird though that it's only reproducible on master but not in v0.18.1. So I think there may be a real bug.

**Comment by borg323** [comment] 2018-10-26 16:17
The commit I pointed above is right before the OpenCL tuner fix, which is the only relevant OpenCL backend change since 18.1. The only other change is my patch to set CL_HPP_TARGET_OPENCL_VERSION to 110, but this is conditional on win32 only.

**Comment by nblaxall** [comment] 2018-10-26 19:50
I tested 636d32 and it does not have the issue:
https://pastebin.com/PQivPB3s

**Comment by nblaxall** [comment] 2018-10-26 20:08
borg got me to test:
https://github.com/LeelaChessZero/lc0/commit/ab9fdd64ae2e091db79c6dc15b4a6ef2e8bd8880
... and it does display the issue:
https://pastebin.com/52fqd5qQ
(ie wants to lose the bishop from 4340 nodes)

**Comment by Ttl** [comment] 2018-10-27 03:03
Can you post the contents of `leelaz_opencl_tuning` file?

**Comment by nblaxall** [comment] 2018-10-27 03:28
Ttl ... for my Mojave macbook the file is:
`$ cat ./leelaz_opencl_tuning
0;XgemmBatched;256;16;256;256; -DKWG=32 -DKWI=2 -DMDIMA=8 -DMDIMC=8 -DMWG=32 -DNDIMB=8 -DNDIMC=8 -DNWG=16 -DSA=1 -DSB=1 -DSTRM=0 -DSTRN=0 -DVWM=4 -DVWN=2;OpenCL: Intel Inc. Intel(R) Iris(TM) Graphics 6100 @ 1050MHz
0;XgemmBatched;256;256;256;16; -DKWG=32 -DKWI=2 -DMDIMA=16 -DMDIMC=16 -DMWG=64 -DNDIMB=8 -DNDIMC=8 -DNWG=64 -DSA=1 -DSB=1 -DSTRM=0 -DSTRN=0 -DVWM=4 -DVWN=4;OpenCL: Intel Inc. Intel(R) Iris(TM) Graphics 6100 @ 1050MHz`

**Comment by Ttl** [comment] 2018-10-27 03:46
It works for me with your tuning file for me so there shouldn't be any issues with the code. It seems to me that the OpenCL drivers are broken like on many other Macs.

**Comment by nblaxall** [comment] 2018-10-27 03:49
Yep.  Since OpenCL works on my older mac, should this be closed or whatever? ... or what?

**Comment by borg323** [comment] 2018-10-27 07:03
The working macbook has with an AMD gpu. I would wait for a few more test reports using macos, maybe we'll find a pattern that we can detect and at least print a warning.

**Comment by mooskagh** [comment] 2019-01-01 22:53
Haven't been reported since long, closing this.

**Closed by mooskagh** 2019-01-01 22:53 UTC
