### ISSUE TITLE
Bad castling rights in user-provided FEN strings

### ISSUE THREAD

**Issue by fohristiwhirl** [LeelaChessZero/lc0#896] opened 2019-06-22 13:38 UTC
I think a fairly common error (well, I've done it) when a user is inputting a FEN is to have impossible castling rights. For example, this position:

`r2qk2r/pppppppp/8/8/8/8/PPPPPPPP/R2KQ2R w KQkq - 0 1`

Clearly White cannot actually have KQ castling rights, but Lc0 does not detect a problem, and in fact Leela (net 42606 anyway) reports `d1g1` as the best move!

`info string d1g1  (103 ) N:    3849 (+162) (P:  8.29%) (Q:  0.01778) (D:  0.000) (U: 0.00975) (Q+U:  0.02753) (V:  0.0645)`

I see the FEN parser detects bad *en passant* squares, it would be great if it could check castling rights too. For example, if the white rook is not present on h1, delete "K". If the white king is not present on e1, delete "K" and "Q". *Et cetera*.

I think this would have to happen approximately [here](https://github.com/LeelaChessZero/lc0/blob/5b7e85958f7b9d40df707777e2d2a52b72a0bea6/src/chess/board.cc#L981). Unfortunately my ability to write (or even read) C++ is near-nil, or I'd submit a patch.

**Comment by MelleKoning** [comment] 2019-07-07 19:22
Adding the actual position of Rooks and the King to the code to prevent this could be done, but that would have to be adjusted again if Lc0 would be supporting variants like Chess960, I'm afraid. You basically give lc0 a wrong FEN. 
Garbage in, garbage out. For now it's not a bug, it's a feature.

**Comment by mooskagh** [comment] 2019-07-16 18:46
I think it's low priority but still worth fixing.
So if someone needs some easy way to touch the code, that would be a good issue to fix.

**Comment by AlexisOlson** [comment] 2019-09-14 03:37
With #943 merged, this should be closed now, right?

**Closed** 2019-09-20 16:52 UTC
Labels: good first issue
