### ISSUE TITLE
0.24rc2 arm7a issue

### ISSUE THREAD

**Issue by AlexB123** [LeelaChessZero/lc0#1104] opened 2020-03-02 13:43 UTC
Hello! 0.24rc2 arm7a doesn't work at all, did you change API level or it contains bug?

**Comment by lealgo** [comment] 2020-03-02 14:15
> Hello! 0.24rc2 arm7a doesn't work at all, did you change API level or it contains bug?

Yes, this is the situation: We had to up the API level to 24 (Android 7) on the armv7a. Since the project moved to c++17 we're using a more recent Android NDK, unfortunately newer NDK's fail to build for lower API. We don't have a solution for that yet, I'm afraid you'll have to keep using the older builds for armv7a. Sorry.

**Comment by AlexB123** [comment] 2020-03-02 16:19
> 
> 
> > Hello! 0.24rc2 arm7a doesn't work at all, did you change API level or it contains bug?
> 
> Hi, the armv7a build works but it's targeting the API level 24 (Android 7). This is the situation: Since the project moved to c++17 we're using a more recent Android NDK. Unfortunately newer NDK's fail to build the project for lower API levels. We don't have a solution for that yet. Until that I'm afraid you'll have to keep using the older builds for armv7a. Sorry.

NDK r18 have no problem with C++17.  You must to create 2 different toolchains, android-standalone-32 for arm7 with API 16, and android-standalone-64 for arm8 with API 21. https://developer.android.com/ndk/guides/standalone_toolchain

**Comment by lealgo** [comment] 2020-03-02 16:36
> NDK r18 have no problem with C++17. You must to create 2 different toolchains, android-standalone-32 for arm7 with API 16, and android-standalone-64 for arm8 with API 21. https://developer.android.com/ndk/guides/standalone_toolchain

Yes, I'm aware of that. The problem has nothing to do with c++17. The c++17 change just forced us to use newer NDK's (We're currently building with r17). The problem is with newer NDK's while targeting older API levels. It's better explained here:

https://android.googlesource.com/platform/bionic/+/master/docs/32-bit-abi.md

**Comment by lealgo** [comment] 2020-03-08 21:49
@AlexB123 

I'm investigating this issue again, could you please try with this build:

[lc0-eigen-aarmv7a.zip](https://github.com/LeelaChessZero/lc0/files/4303923/lc0-eigen-aarmv7a.zip)

**Comment by lealgo** [comment] 2020-03-16 14:33
@AlexB123 

Version 0.24.1 has been released and it has a lower API requirement for `armv7`. Can you try it and let us know if it works?

**Comment by Naphthalin** [comment] 2020-05-01 11:43
Pinging @AlexB123 again for feedback on a potential fix.

**Comment by mooskagh** [comment] 2021-06-27 19:10
Closing as the issue author didn't respond with more information for quite a while.

Feel free to reopen if you have new data.

**Closed by mooskagh** 2021-06-27 19:10 UTC
