### ISSUE TITLE
MCTS+NN 2-fold preference hypothesis

### ISSUE THREAD

**Issue by TesseractA** [LeelaChessZero/lc0#962] opened 2019-09-30 21:50 UTC
Though we may already have recent PRs like certainty propagation and the 'moves left' head that 'resolve' this issue outside of training, I'd like to explain this issue for reference because those solutions may risk sharpening of policy in training. I have a hypothesis and some potential evidence to back it up.

Hypothesis: A 2-fold repetition is the manifestation of leela's preference to get into familiar (and similar) winning positions. 
The network is less familiar with some particular winning positions in training, making it less certain about some potentially faster-winning continuations. MCTS Search-averaging score is greatest with these familiarly-winning positions. The effect is that search will stay in the 'local minimum' that the network likes the most, meaning 2-folds get played as the network is more certain about that win. When this happens in training, policy will inadvertently have leela look for the similar positions too. Hence, the cycle of 'familiarly winning positions' repeats.

Predictions: 
-If we abandoned policy and went to Q-prediction for each subsequent move, we'd still have the issue of 'familiarly-winning' positions, but potentially less of an issue since the network's choice is less influenced by deliberately predicting 2-folds.
-As a position encroaches on the 50 move rule, it becomes less certain and will bridge the 'local minimum' that search keeps it in to find a sooner terminal winning position; something with fewer 2-folds.

Examples: 
-KQvKR tablebase playouts and Lc0's evaluation during those playouts. Leela's evaluation dips significantly when the tablebase plays not-preferred moves.
-I am also reminded of games like this where near the end, Lc0's evaluation dips dramatically for a few moves in evaluation of a winning KQPPvKQ endgame. https://www.chess.com/computer-chess-championship#event=ccc-9-the-gauntlet-qualification&game=83

**Comment by Naphthalin** [comment] 2020-05-01 10:48
I think one of the causes is much more basic: evals are often depth-dependent for Leela, and can either grow or shrink; whenever the eval of a move shrinks at more nodes, repeating moves first seems more favourable than playing the move directly, as with the same N, fewer nodes will go into the deeper exloration of the actual line (so it is evaluated more favorable), and some additional nodes are spent on the opponent's alternative answers to the repeating move, which are also more favorable than accepting the repetition (because otherwise the opponent had a better move than accepting the repetition).

A proper handling of 2-fold repetition draws would solve this, but so far no theoretical solution solves all cases needed for MCTS. #1161

**Comment by mooskagh** [comment] 2020-05-03 09:15
Closing as it's getting no traction for several months. (and not really actionable either)

**Closed by mooskagh** 2020-05-03 09:15 UTC

**Comment by TesseractA** [comment] 2020-05-03 13:18
Good decision. Still not sure how to fix this issue--it's a NN preference, which probably belongs in issues for lczero training.
