### ISSUE TITLE
LC0 only ~60% GPU load when running test suites. BUG

### ISSUE THREAD

**Issue by Chess321** [LeelaChessZero/lc0#1121] opened 2020-03-10 08:18 UTC
Fritz GUI
LC0 v0.24.0-rc2 
2x RTX 2080 Ti
4 of 6 CPU cores
8 of 64 GB RAM
Tested with different nets and net size.

When running infinite analysis I have ~90% GPU load.
[logfile.txt](https://github.com/LeelaChessZero/lc0/files/4310982/logfile.txt)

When running different test suites I have in the first position ~90% GPU load but in the other positions I have only ~60% GPU load.
[logfile.txt](https://github.com/LeelaChessZero/lc0/files/4311034/logfile.txt)

**Comment by mooskagh** [comment] 2020-03-10 20:49
It takes some time until the search is able to find enough work for GPUs, that's why for the first 100000 nodes or so the GPU load is low.
There are attempts to fix that, but it's a large and not an easy effort and it's more in "improvements" realm than on "bug".

You can however tune some settings be able to get larger nps from the very beginning or get up to speed faster.
For that I recommend to join our discord chat https://discord.gg/pKujYxD and ask there in #help channel.

I'm closing this issue for now as it's really not a bug but a known limitation.

**Closed by mooskagh** 2020-03-10 20:49 UTC
