### ISSUE TITLE
Lc0 cudnn not working on GT650M on OSX - out of memory

### ISSUE THREAD

**Issue by ArminHHJ** [LeelaChessZero/lc0#329] opened 2018-09-01 22:05 UTC
After compiling and starting the lc0 v0.17. cuddn MAC is hanging and need a hardreset. opencl version is running fine.
The only hint after the restart is this error message in the terminal:
"error CUDA error: out of memory (../../src/neural/network_cudnn.cu:501)". after the restart in the terminal.

see also in https://groups.google.com/forum/#!topic/lczero/mHbEH-ufN6Q

**Comment by borg323** [comment] 2018-09-03 22:05
Can you try adding the option `--backend-opts=batch_size=4` to lc0 to see if it helps? If it does, you can also try `--backend-opts=batch_size=8`.

**Comment by mooskagh** [comment] 2018-09-15 07:26
I think we can at least reduce cudnn minibatch size from 1024 to 256 or 512 by default.
When people increase mcts minibatch size, they will also have to increase cudnn.

"Correct" solution that I had in mind is that every backend would report its capabilities (parallelism, optimal and maximum batch size etc), but that's surely preempted by other tasks and won't happen soon.

**Comment by borg323** [comment] 2018-09-15 07:58
The master branch now supports the max_batch parameter for cudnn. You can try `--backend-opts=max_batch=512` and if it still runs out of memory `--backend-opts=max_batch=256`.

**Comment by ArminHHJ** [comment] 2018-09-20 19:38
I compiled the v0.18-dev from 20.09.18
Lc0 starting in terminal:
Works fine with --backend-opts=max_batch=256, when starting in terminal! 
With --backend-opts=max_batch=512 the Mac is hangig. 
Starting without this option the Mac is hangig.

Using the GUI it is necessary to set the option opts=max_batch=256 in the NN backend parameters, otherwise the Mac will hanging.

lc0 cuda runs 7-9 tme faster then opencl!

thx

**Comment by borg323** [comment] 2018-09-20 20:03
When you say the Mac is hanging, you mean you need to reboot it?

**Comment by ArminHHJ** [comment] 2018-09-21 07:58
yes, only the mouse cursor is moving, but no response by clicking. Sometime the screen is flickering or blinking in black. Hardrest is necesarry (power off)...

**Comment by borg323** [comment] 2018-09-21 08:18
@ankan-ban any ideas how we can improve this?

**Comment by ArminHHJ** [comment] 2018-09-21 13:48
Unfortunately I don't know what these settings mean. When using opencl, the problem does not occur. It may be a specific feature in cuda and/or in collaboration with this graphics card and its memory. There is a Mac user where it works without this option (acepoint, see the link above).

The first time you start opencl (out-of-the-box, no entries configured in UCI), a leelaz_opencl_tuning file is created.
Content v0.18-dev:  
0;XgemmBatched;256;16;256;256; -DKWG=32 -DKWI=2 -DMDIMA=16 -DMDIMC=16 -DMWG=64 -DNDIMB=8 -DNDIMC=8 -DNWG=16 -DSA=1 -DSB=1 -DSTRM=0 -DSTRN=0 -DVWM=4 -DVWN=2;OpenCL: NVIDIA GeForce GT 650M @ 810MHz

Content v0.17
0;XgemmBatched;256;16;256;16; -DKWG=32 -DKWI=2 -DMDIMA=16 -DMDIMC=16 -DMWG=64 -DNDIMB=8 -DNDIMC=8 -DNWG=16 -DSA=1 -DSB=1 -DSTRM=0 -DSTRN=0 -DVWM=4 -DVWN=2;OpenCL: NVIDIA GeForce GT 650M @ 810MHz

Maybe this would also be a way to start with cudnn?


Translated with www.DeepL.com/Translator

**Comment by ankan-ban** [comment] 2018-09-22 04:05
I think the max_batch param is good enough, but I agree that it's bad experience for users especially if they have to restart the system. 
The hang and need for hard-reset is likely a driver bug in Mac. In windows/linux, the app exits with OOM failure which is the expected behaviour (maybe we can add some message to let the users know about max_batch option).

One possible solution could be to use cudaMemGetInfo() function to query the amount of free memory, and keep track of all cudaMalloc calls made by the backend to make sure it doesn't exceed 80% or so of the amount queried. If it fails, keep iterating with lower max_batch_size. This will probably require some refactoring to do all cudaMallocs at one place (I think scratch_mem_ and tensor_mem_[] are the only ones that need to be tracked).

**Comment by mooskagh** [comment] 2019-01-01 22:30
Does this issue still exist?

**Comment by oscardssmith** [comment] 2019-02-11 04:35
I think we can probably close this as it seems to be dead.

**Closed** 2019-02-16 18:15 UTC
Labels: bug
