### ISSUE TITLE
Unexpected Behavior Change With Recent lc0 Versions

### ISSUE THREAD

**Issue by GBeauregard** [LeelaChessZero/lc0#91] opened 2018-06-18 20:32 UTC
Using main net ID 421, with the latest versions of lc0 master (Mon, Jun 18), and the latest crem builds, run the following test position, which is a mate in 1. 

`1. b3 g6 2. Bb2 Nf6 3. g3 Bg7 4. Nf3 c5 5. c4 Nc6 6. Bg2 d6 7. O-O e5 8. Nc3 O-O 9. d3 Rb8 10. Qd2 a6 11. Ng5 h6 12. Nge4 Nh5 13. Nd5 f5 14. Nec3 f4 15. Kh1 Be6 16. Bf3 Nd4 17. Bxh5 gxh5 18. gxf4 Qh4 19. Ne4 exf4 20. Rg1 Kh7 21. Qa5 b6 22. Qxa6 Rf7 23. Nxd6 Rd7 24. Nxb6 Rxd6 25. Rxg7+ Kxg7 26. Qa7+ Bf7 27. Bxd4+ Kh7`

At low node counts ~(0-1000), ID 421 correctly finds the mate in 1 (Qxf7#)
At higher node counts, ~>1000 nodes, ID 421 unfinds the mate in 1 (eventually settles on Qxb8)

On older versions of lc0 (~a few weeks old; I haven't tracked down the exact change at this time), ID 421 finds the mate in 1 and keeps it. This suggests recent changes to lc0 are causing the change.

LCZero v0.10 also finds the mate in 1 and keeps it fine.

I found this position because the incorrect analysis caused Leela to lose a machine match I was running (it moved into the mate-in-1 by playing 27. ...Kh7???).

**Comment by MTGOStark** [comment] 2018-06-18 21:04
It starts with this one: lc0-win-20180609-cuda92-cudnn714-00.7z
With 0604 build, it finds it both with and without history: 

https://gyazo.com/8816153bf17898091b4399f327466c9e

https://gyazo.com/5caad55050c013c968b650d1e27f5c49

With 0609-00 build: 

https://gyazo.com/ddd29a6472df6e75a867279162ac4056

**Comment by Tilps** [comment] 2018-06-18 22:35
Speculating...
https://github.com/LeelaChessZero/lc0/commit/77081343602cd34ad3b1b4b39bcd56a63b3e0013 seems to be in the 0604 to 0609 window.
Maybe the ASilver tune doesn't work well with the latest nets? This be easy to test.

Alternatively I'm vaguely concerned about 
node_to_process.v = node_to_process.node->GetTerminalNodeValue();
In the backpropogate-gamma/node weight loss patch.  Are we sure that shouldn't have a negative sign?

**Comment by SashaMN** [comment] 2018-06-18 23:29
I guess this commit causes the problem: https://github.com/LeelaChessZero/lc0/commit/a4893ef1dfc650d6a189ff7665eae975ff19b9dd
Prev commit looks fine.

**Comment by dubslow** [comment] 2018-06-19 00:20
Has anyone converted that move list into long-algebraic notation?

**Comment by dubslow** [comment] 2018-06-19 00:47
I am able to reproduce. Looks like it will be fairly simple to locate and fix, here are the top three moves from a search:

```
info string d4c5  (760 ) N:      59 (+ 0) (V:  44.76%) (P:  3.42%) (Q:  0.53033) (U: 0.05819) (Q+U:  0.58852) 
info string a7f7  (1398) N:      61 (+ 0) (V:   0.00%) (P: 41.24%) (Q:  0.00000) (U: 0.67926) (Q+U:  0.67926) 
info string a7b8  (1402) N:     662 (+ 3) (V:  50.04%) (P:  6.40%) (Q:  0.66858) (U: 0.00981) (Q+U:  0.67839) ```

That V value is obviously incorrect.

**Comment by dubslow** [comment] 2018-06-19 01:02
I find it highly unlikely that a4893ef is the problem -- far more likely that the most recent merged PR about slimming down `Node` is the problem. Working it now.

**Comment by Tilps** [comment] 2018-06-19 01:09
position startpos moves b2b3 g7g6 c1b2 g8f6 g2g3 f8g7 g1f3 c7c5 c2c4 b8c6 f1g2 d7d6 e1g1 e7e5 b1c3 e8g8 d2d3 a8b8 d1d2 a7a6 f3g5 h7h6 g5e4 f6h5 c3d5 f7f5 e4c3 f5f4 g1h1 c8e6 g2f3 c6d4 f3h5 g6h5 g3f4 d8h4 c3e4 e5f4 f1g1 g8h7 d2a5 b7b6 a5a6 f8f7 e4d6 f7d7 d5b6 d7d6 g1g7 h7g7 a6a7 e6f7 b2d4 g7h7
in case it saves someone else a few seconds.

**Comment by dubslow** [comment] 2018-06-19 01:11
Where was that an hour ago :P

**Comment by Tilps** [comment] 2018-06-19 02:11
So the problem is FetchNNResults now also populates node_to_process.v for terminals. And node_to_process.v is what is used in the back updating flow.
However the first line of FetchNNResults skips all its content if there were no computations done.  Thus if a batch only contains terminals, .v is never populated. (And is I think uninitialised memory, just happens to be close to 0 for some reason...)
Commenting out the first line of FetchNNResults solves the problem.

Alternatively the v property on node_to_process could probably be removed again since v was re-added to node.

**Closed** 2018-06-19 03:16 UTC
Labels: bug
