### ISSUE TITLE
Heads up for macOS users - "errno=22"  error

### ISSUE THREAD

**Issue by MichaelB7** [LeelaChessZero/lc0#1036] opened 2019-12-06 06:26 UTC
If you upgrade to Meson 5.2, your build will fail with this message:
```
ld: can't map file, errno=22 file '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/OpenCL.framework' for architecture x86_64
```

If you use macPorts, simply do this to fix until Meson is updated:
```
 sudo port activate meson @0.51.2_0
--->  Computing dependencies for meson
--->  Deactivating meson @0.52.0_0
--->  Cleaning meson
--->  Activating meson @0.51.2_0
```

**Comment by Mardak** [comment] 2019-12-10 18:19
Dupe of #972

**Closed by Mardak** 2019-12-10 18:19 UTC
