### ISSUE TITLE
Ubuntu 16.04 compiling problems

### ISSUE THREAD

**Issue by pw31** [LeelaChessZero/lc0#1043] opened 2019-12-26 14:53 UTC
I tried to compile as instructed in README, section Ubuntu 16.04, without success, see
below, using tcsh shell.  Any idea what's wrong?

Thanks, Peter

prodimo:~/chess/engines/LeelaChessZero-lc0-89c516b> setenv CC /usr/bin/clang-6.0
prodimo:~/chess/engines/LeelaChessZero-lc0-89c516b> setenv CXX /usr/bin/clang++-6.0 
prodimo:~/chess/engines/LeelaChessZero-lc0-89c516b> setenv INSTALL_PREFIX ~/bin   
prodimo:~/chess/engines/LeelaChessZero-lc0-89c516b> sh ./build.sh 
The Meson build system
Version: 0.52.1
Source dir: /data/data/pw31/chess/engines/LeelaChessZero-lc0-89c516b
Build dir: /data/data/pw31/chess/engines/LeelaChessZero-lc0-89c516b/build/release
Build type: native build
Project name: lc0
Project version: undefined
C++ compiler for the host machine: /usr/bin/clang++-6.0 (clang 6.0.1-svn334776 "clang version 6.0.1-svn334776-1~exp1~20190309042730.123 (branches/release_60)")
C++ linker for the host machine: GNU ld.bfd 2.26.1
Host machine cpu family: x86_64
Host machine cpu: x86_64
WARNING: Consider using the builtin warning_level option instead of adding warning flags by hand.
Library libprotobuf found: YES
Program protoc found: YES (/usr/bin/protoc)
Library pthread found: YES
Library dl found: YES
Library libtensorflow_cc found: NO
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Found CMake: /usr/bin/cmake (3.5.1)
Run-time dependency accelerate found: NO (tried pkgconfig and cmake)
Library mkl_rt found: NO
Library mklml found: NO
Library openblas.dll found: NO
Library openblas found: NO
Program ispc found: NO
Library OpenCL found: YES
Run-time dependency opencl found: YES 2.1
Library cublas found: NO
Library cudnn found: NO
Library cudart found: NO
Program nvcc found: NO
Program /usr/local/cuda/bin/nvcc found: NO
Program /opt/cuda/bin/nvcc found: NO
Run-time dependency zlib found: YES 1.2.8
Run-time dependency GTest found: NO (tried pkgconfig and system)
Looking for a fallback subproject for the dependency gtest
Downloading gtest source from https://github.com/google/googletest/archive/release-1.8.0.zip
Downloading file of unknown size.
Downloading gtest patch from https://wrapdb.mesonbuild.com/v1/projects/gtest/1.8.0/5/get_zip
Downloading: 100%|██████████████████████████████████████| 2084/2084 [00:00<00:00, 1237215.79bytes/s]

|Executing subproject gtest method meson 
|
|Project name: gtest
|Project version: 1.8.0
|C++ compiler for the host machine: /usr/bin/clang++-6.0 (clang 6.0.1-svn334776 "clang version 6.0.1-svn334776-1~exp1~20190309042730.123 (branches/release_60)")
|C++ linker for the host machine: GNU ld.bfd 2.26.1
|Run-time dependency threads found: YES 
|Dependency threads found: YES (cached)
|Dependency threads found: YES (cached)
|Dependency threads found: YES (cached)
|Build targets in project: 1
|Subproject gtest finished.

Dependency gtest from subproject subprojects/gtest found: YES
Build targets in project: 8
Found ninja-1.5.1 at /usr/bin/ninja
./build.sh: 24: ./build.sh: pushd: not found

**Comment by mooskagh** [comment] 2019-12-26 15:33
You run the script with `sh`, which doesn't have `pushd` command.
`bash` should be used instead (just typing `./build.sh` should also work as the script starts with `#!/usr/bin/env bash`)

**Comment by pw31** [comment] 2019-12-26 16:06
@mooskagh : many thanks, "bash ./build.sh" seems to work fine.  Just wonder about the wisdom to call a script .sh when it's a bash-script.  Why not call it build.bsh?

**Comment by Naphthalin** [comment] 2020-05-01 11:12
Not a Lc0 issue, as everything works as intended. Closing now.

**Closed by Naphthalin** 2020-05-01 11:12 UTC
