### ISSUE TITLE
v0.19.0-rc5, ponder on loses on time bug

### ISSUE THREAD

**Issue by all12** [LeelaChessZero/lc0#519] opened 2018-11-17 22:46 UTC
Loses on time:
[Aquarium 2018, ponder on, 1+1, LogFile.txt](https://github.com/LeelaChessZero/lc0/files/2592332/Aquarium.2018.ponder.on.1%2B1.LogFile.txt)

**Comment by all12** [comment] 2018-11-17 23:00
It also loses on time with ponder off:
[Aquarium 2018, ponder off, 1+1, LogFile.txt](https://github.com/LeelaChessZero/lc0/files/2592348/Aquarium.2018.ponder.off.1%2B1.LogFile.txt)

**Comment by borg323** [comment] 2018-11-18 10:07
Can you check if #522 helps? The executable to test is [this one](https://ci.appveyor.com/api/buildjobs/uc3ne262dhyubt51/artifacts/build%2Flc0.exe).

**Comment by borg323** [comment] 2018-11-18 15:51
Can you try to reproduce this crash using rc5? The additional code in the test executable is only called later in the search, so this is strange.

**Comment by all12** [comment] 2018-11-18 19:44
I tried it again with ponder off and much more games.

We have no crash:)
And no loses on time:)

I splitted the logfile in 2 parts because it was to big for upload.
[Aquarium 2018, ponder off, 1+1, LogFile.txt](https://github.com/LeelaChessZero/lc0/files/2593144/Aquarium.2018.ponder.off.1%2B1.LogFile.txt)
[Aquarium 2018, ponder off, 1+1, LogFile - part 2.txt](https://github.com/LeelaChessZero/lc0/files/2593149/Aquarium.2018.ponder.off.1%2B1.LogFile.-.part.2.txt)

**Comment by borg323** [comment] 2018-11-18 21:46
Looking at the latest log with ponder on I see the following pattern (worst case shown):
```
1118 12:10:17.430507 2404 ..\src/chess/uciloop.cc:131] >> go ponder btime 15263 binc 1000
...
1118 12:10:17.430870 2404 ..\src/chess/uciloop.cc:131] >> stop
...
1118 12:10:17.430973 4704 ..\src/chess/uciloop.cc:218] << info depth 4 seldepth 4 time 0 nodes 3015 score cp -261 hashfull 755 nps 0 tbhits 0 pv b2b5 c7a7 b5h5 c1g1 g6f6 a7a6 f6e7 g1g7 h5h3 g7g2 h3f3 g2e2 e7f8
...
1118 12:10:17.432356 4704 ..\src/chess/uciloop.cc:218] << bestmove e2d2 ponder b2b5
...
1118 12:10:17.432936 2404 ..\src/chess/uciloop.cc:131] >> position startpos moves a2a3 e7e5 e2e4 g8f6 b1c3 d7d5 e4d5 f6d5 f1c4 d5c3 d1f3 d8f6 f3c3 f8d6 d2d3 b8c6 g1e2 e8g8 e1g1 c6d4 e2g3 h7h5 g1h1 f6g6 g3e4 h5h4 f2f3 h4h3 f1f2 b7b5 c4d5 c7c6 d5a2 c8e6 c1e3 e6a2 e3d4 e5d4 c3c6 a8d8 a1a2 g6f5 e4d6 f5e6 a2a1 d8d6 c6b5 d6b6 b5g5 b6b2 g2h3 f8c8 a1c1 e6e3 g5e3 d4e3 f2e2 c8c3 e2e3 c3a3 e3e8 g8h7 e8c8 a7a5 h1g1 a5a4 c8c7 h7g6 g1f1 a3a2 f1e2 a4a3 c1g1
...
1118 12:10:17.441539 2404 ..\src/chess/uciloop.cc:131] >> go btime 14951 binc 1000
```
The time available is inexplicably reduced by 312 ms between `go ponder btime 15263` and `go btime 14951`. I suspect aquarium is doing something similar with `ponderhit` which may lead to time losses since the engine is not informed of this adjustment.

**Comment by borg323** [comment] 2018-11-18 22:49
@all12 I don't see anything else in the logs, please try again to set `MoveOverheadMs` to 500 with the test executable.

**Comment by all12** [comment] 2018-11-18 22:55
Ok I will try ponder on and MoveOverheadMs to 500 with the test executable.

**Comment by all12** [comment] 2018-11-19 20:10
@borg323,

MoveOverheadMs set to 500 is perfect and a great improvement. 
Aquarium 2018, ponder on, 1+1 tc and no loses on time:)

[LogFile part 1.txt](https://github.com/LeelaChessZero/lc0/files/2596881/LogFile.part.1.txt)
[LogFile part 2.txt](https://github.com/LeelaChessZero/lc0/files/2596889/LogFile.part.2.txt)
[LogFile part 3.txt](https://github.com/LeelaChessZero/lc0/files/2596901/LogFile.part.3.txt)

**Comment by borg323** [comment] 2018-11-20 23:18
Closing this and the related ones, if you run into more problems with the final v0.19 release, please open a new issue.

**Closed by borg323** 2018-11-20 23:18 UTC
