### ISSUE TITLE
Leela's end game

### ISSUE THREAD

**Issue by khuttur** [LeelaChessZero/lc0#1254] opened 2020-04-30 03:13 UTC
Hi,
It seems that lc0 has a bug in endgame playing on android device. Lc0 plays very poorly endgame. It seems that she has no knowledge of endgame!
Please solve this bug.
See this,
http://s000.tinyupload.com/?file_id=74172443691161865248

**Comment by fohristiwhirl** [comment] 2020-04-30 13:32
The problem is not that Leela doesn't know how to win, but that Leela has nothing making her prefer short victories over long ones.

**Comment by Naphthalin** [comment] 2020-05-04 18:36
Marking this as a duplicate of the more elaborate #1229.

**Closed by Naphthalin** 2020-05-04 18:36 UTC
